### ISSUE TITLE
Using regular id's

### ISSUE THREAD

**Issue by abarax** [api-hogs/ember-data-offline#72]
Hi,

I am trying to use this framework with an existing ember application. In an attempt to keep things simple of now, I want to just drop the framework in to the existing application but one of the things I am having trouble with is the use of id's.  I understand that hash's are being used to avoid duplicates and sync errors across offline/online scenarios but is there any way to change this behaviour? 

Where is this use of hashes for id's being dictated?

 I realise I will need to change to use hashes for id's in the future, but for now I just want to get it working regardless of sync issues.

Any help you could provide is much appreciated, thanks.

**Comment by igorrKurr** [comment]
Hi, @abarax!
Can you please provide some example of your problem?

**Comment by abarax** [comment]
Basically when I attempt to save a record to my REST backend the payload is this:

    {
        id: "n2r9h",
        name: "another",
        children: ["undefined"]
    }

The id is a hash value instead of an integer.  The relationship id's are undefined presumably due to the same reason.  I would like to use integers for now, is there any way to change this? Happy to dig in to the code.

**Comment by igorrKurr** [comment]
Ok, you get such `id` because of `ember-localforage-adapter` which we currently depend on. So, it seems that good solution is to extend it and overwrite `generateIdForRecord` method. You can start by just copying https://github.com/api-hogs/ember-data-offline/blob/master/addon/adapters/base.js this adapter and playing with offline adapter there - https://github.com/api-hogs/ember-data-offline/blob/master/addon/adapters/base.js#L89.
But I can recommend you to just ignore that localforage-generated `id` and use your backend `id` (from mysql,etc.). `Ember-data-offline` can handle such behavior by default, so you can just don't worry about ids. Here you can see how it is implemented - https://github.com/api-hogs/ember-data-offline/blob/master/addon/jobs/rest.js#L125

**Comment by abarax** [comment]
Thanks for pointing me in the right direction. Very helpful.

**Comment by igorrKurr** [comment]
seems like resolved, i'll close
